Add grid
wolox-training/gs-react pull request #10
Opened 2019-09-26 20:24 UTC by guilleSequeiraWolox

## Summary

Add grid

## Screenshots

![grid](https://user-images.githubusercontent.com/42941989/65722363-8009b180-e082-11e9-939c-648f3d1e8303.gif)

## Trello Card

https://trello.com/c/ULPh3XYv/12-redise%C3%B1o-de-la-p%C3%A1gina

2019-09-26 21:11 UTC, gabrielizalo approved these changes

2019-09-27 20:31 UTC, gabrielizalo requested changes

2019-09-27 20:31 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +  grid-template-areas:
Please move `grid-template-areas` before `grid-template-columns`.

2019-09-27 20:31 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +    grid-template-areas:
Move `grid-template-areas` before `grid-template-columns`.

2019-09-27 20:31 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +      left: 4px;
Can `4px` be `5px`?

2019-09-27 21:19 UTC, Dorian30 requested changes

2019-09-27 21:19 UTC, Dorian30 commented on maquetado/scss/description.scss
> +  margin-top: 20px;
Use the shorthand 

```suggestion
  margin: 20px 0 14px 10px;
```

2019-09-27 21:19 UTC, Dorian30 commented on maquetado/scss/description.scss
> +.description-content-book-content {
Content-book-content ? :eyes:

2019-09-30 18:11 UTC, gabrielizalo approved these changes

2019-09-30 18:11 UTC, gabrielizalo commented on maquetado/detailOfBooks.html
> +      <h2 class="description-book-title">Titulo del Libro</h2>
Please add tilde to `Titulo` in this way `Título`.

2019-09-30 23:23 UTC, Dorian30 approved these changes

2019-10-02 19:52 UTC, merged