Add books
wolox-training/gs-react pull request #18
Opened 2019-10-30 21:18 UTC by guilleSequeiraWolox

## Summary

Add list of books.

## Screenshots

![LIST OF BOOKS](https://user-images.githubusercontent.com/42941989/67899687-97383500-fb41-11e9-8939-89dcdf2b45ae.gif)

## Trello Card

https://trello.com/c/ro0n7jlq/68-book-list-auth-header

2019-10-30 21:41 UTC, LucasZibell requested changes

2019-10-30 21:41 UTC, LucasZibell commented on react/wbooks/src/app/components/PublicRoute/index.js
> +        localStorage.getItem('tokenId') ? <Redirect to={redirect} /> : <Component {...props} />
You can use only 1 component `Route` and pass a prop `private`. If it is private you negate this condition. And you end up using the same component for the two routes

2019-10-30 21:41 UTC, LucasZibell commented on react/wbooks/src/app/index.js
> +      <PublicRoute path="/signUp" component={SignUp} redirect="/home" />
specify the redirect only when neccesary. And keep '/home' and '/' as the default redirect on the `Route` component

2019-10-30 21:41 UTC, LucasZibell commented on react/wbooks/src/app/screens/Home/components/Book/index.js
> +    [author, title]
Hey, don't use useMemo for renders. React already renders this only when title and author change. The useMemo hook should be use for complicated calculations before a render

2019-10-30 21:41 UTC, LucasZibell commented on react/wbooks/src/app/screens/Home/index.js
> +  localStorage.setItem('tokenId', '');
arrow function

2019-11-11 18:34 UTC, mariadelacamara commented on react/wbooks/src/app/index.js
> +      <PrivateRoute exact path="/home" component={Home} />
why do you write `exact` path here?

2019-12-17 15:29 UTC, LucasZibell approved these changes

2019-12-17 15:29 UTC, merged