add-list-of-books
wolox-training/gs-react pull request #4
Opened 2019-09-18 20:00 UTC by guilleSequeiraWolox

## Summary

I added list of books.

## Screenshots

![gif](https://user-images.githubusercontent.com/42941989/65181563-b4072600-da35-11e9-9805-28066b3c7686.gif)

## Trello Card

https://trello.com/c/MAbYvJNA/30-listado-de-libros

2019-09-18 20:31 UTC, gabrielizalo requested changes

2019-09-18 20:31 UTC, gabrielizalo commented on maquetado/scss/detail.scss
> +  font-size: 16px;
Can it be `15px`?

2019-09-18 20:31 UTC, gabrielizalo commented on maquetado/scss/detail.scss
> +  line-height: 18px;
Can it be `20px`?

2019-09-18 20:31 UTC, gabrielizalo commented on maquetado/scss/detail.scss
> +  margin: 30px;
Move `margin` before `max-width`.

2019-09-19 08:40 UTC, Dorian30 requested changes

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +      </li>
There is no need to use ordered or ordered list for this. You usually use these when it comes to a list of links or something like but in cases like this is better to just use divs

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +      </li>
same

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +      </li>
same

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +      </li>
same

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +      <li>
same

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +    </ol>
same

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +      </li>
same

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +      </li>
same

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/index.html
> +    <ol class="list-of-books">
Use a div instead ul and ol are used to wrapped small things like a list of links

2019-09-19 08:40 UTC, Dorian30 commented on maquetado/scss/detail.scss
> +  padding: 30px 30px 50px 30px;
Use the shorthand

```suggestion
  padding: 30px 30px 50px;
```

2019-09-19 20:03 UTC, Dorian30 approved these changes

2019-09-19 20:28 UTC, gabrielizalo approved these changes

2019-09-19 20:28 UTC, gabrielizalo commented on maquetado/scss/detail.scss
> +  margin-bottom: 10px;
Move `margin-bottom` before `margin-top`.

2019-09-19 20:34 UTC, merged