Add Redirection
wolox-training/gs-react pull request #6
Opened 2019-09-23 14:57 UTC by guilleSequeiraWolox

## Summary

Add redirection

## Screenshots

![linking](https://user-images.githubusercontent.com/42941989/65436928-45d9af00-ddf9-11e9-9e98-add92ab4c183.gif)

## Trello Card

https://trello.com/c/QFY46Dqg/33-detalle-de-libro-vi-redirecci%C3%B3n

2019-09-23 15:43 UTC, gabrielizalo requested changes

2019-09-23 15:43 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +    top: calc(70%);
Please move `top` before `width` attribute.

2019-09-23 15:43 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +  margin-bottom: 14px;
Please move `margin-bottom` before `margin-left`.

2019-09-23 15:43 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +  font-family: Roboto;
I think its better to have a fall-back font, so you can change `font-family: Roboto;` for `font-family: Roboto, Helvetica, Arial, sans-serif;`
An in all `font-family` uses.

2019-09-23 15:43 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +  line-height: 40px;
Move `line-height` before `margin-right`.

2019-09-23 15:43 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +  align-items: center;
Move `align-items` as the first attribute.

2019-09-23 15:43 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +  flex-direction: row;
Move `display` and `flex-direction` after `background-color` attribute.

2019-09-23 15:43 UTC, gabrielizalo commented on maquetado/scss/detail.scss
> -    top: calc(70%);
Please move `top` before `width` attribute.

2019-09-23 15:43 UTC, gabrielizalo commented on maquetado/scss/detail.scss
> +  margin-bottom: 5px;
Please move `margin-bottom`  before `padding` attribute.

2019-09-23 20:35 UTC, Dorian30 requested changes

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/detailOfBooks.html
> +    <a class="back-button" onclick="location.href='index.html'">
There is no need to use onclick for this. You can handle the redirect by writing `href="index.html"`

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/detailOfBooks.html
> +    </a>
You can make this simpler. 

Remember that all images that are just there for decorative purposes can be set through a pseudo class instead. For example, you can write: 

```
<a class="back-button" href="index.html">
  Atrás
</a> 
```

Then you can use CSS to set you arrow image with content.

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +      <img class="wolox-image" src="image/LogoWolox.png" alt="Book Image" />
```suggestion
      <img class="wolox-image" src="image/LogoWolox.png" alt="Wolox" />
```

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +      <a class="logout">Logout</a>
Even if you are not going to redirect or use this button yet it is a good idea to set href attribute anyway, like this 

```suggestion
      <a class="logout" href="#">Logout</a>
```

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +        <a onclick="location.href='detailOfBooks.html'">
Same, use `href` instead for this.

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +          <img class="book-image" src="image/book-cover.png" alt="Book Image" />
There is no need to write "image" in alt attribute since it is already a img tag. I would write book cover instead

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +        <a onclick="location.href='detailOfBooks.html'">
Same, use href

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +          <img class="book-image" src="image/book-cover.png" alt="Book Image" />
Same, book cover

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +        <a onclick="location.href='detailOfBooks.html'">
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +          <img class="book-image" src="image/book-cover.png" alt="Book Image" />
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +        <a onclick="location.href='detailOfBooks.html'">
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +          <img class="book-image" src="image/book-cover.png" alt="Book Image" />
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +        <a onclick="location.href='detailOfBooks.html'">
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +          <img class="book-image" src="image/book-cover.png" alt="Book Image" />
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +        <a onclick="location.href='detailOfBooks.html'">
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +          <img class="book-image" src="image/book-cover.png" alt="Book Image" />
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +        <a onclick="location.href='detailOfBooks.html'">
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +          <img class="book-image" src="image/book-cover.png" alt="Book Image" />
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +        <a onclick="location.href='detailOfBooks.html'">
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/index.html
> +          <img class="book-image" src="image/book-cover.png" alt="Book Image" />
Same

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/scss/description.scss
> +    content: "";
```suggestion
    content: '';
```

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/scss/description.scss
> +    top: calc(70%);
There is no need to use calc here. It is better if you use pixels here.

2019-09-23 20:35 UTC, Dorian30 commented on maquetado/scss/description.scss
> +    content: "";
```suggestion
    content: '';
```

2019-09-25 14:13 UTC, guilleSequeiraWolox commented on maquetado/scss/description.scss
> +    content: "";
i apply the change with commit suggestion but vs code auto fix to (" ")

2019-09-25 15:03 UTC, gabrielizalo requested changes

2019-09-25 15:03 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +    top: 30px;
Please move `top` before `width`.

2019-09-25 15:03 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +    background: url("../maquetado/image/badge.png") no-repeat center/contain;
Please move `background` before `content`.

2019-09-25 15:03 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +    background: url("../maquetado/image/back-arrow.png") no-repeat
Please move `backrground` before `content`.

2019-09-25 15:03 UTC, gabrielizalo commented on maquetado/scss/description.scss
> +  align-items: flex-start;
And `align-items` before `background-color`.

2019-09-25 17:38 UTC, Dorian30 approved these changes

2019-09-25 19:05 UTC, gabrielizalo approved these changes

2019-09-25 19:10 UTC, merged